// web/app/(app)/admin/page.tsx
import { apiFetch } from "@/lib/api";
import { Page } from "@/components/ui";

export default async function AdminPage() {
  const overview = await apiFetch<{ users: number; teams: number; projects: number }>("/api/admin/overview");
  return (
    <Page title="管理总览">
      <div className="grid gap-4 sm:grid-cols-3">
        {[
          ["用户", overview.users],
          ["团队", overview.teams],
          ["项目", overview.projects]
        ].map(([label, value]) => (
          <div className="rounded-md border border-slate-200 bg-white p-4" key={label}>
            <p className="text-sm text-slate-500">{label}</p>
            <p className="mt-2 text-3xl font-semibold">{value}</p>
          </div>
        ))}
      </div>
    </Page>
  );
}

// pages/admin/index.vue
<script setup lang="ts">
const { user } = useUserSession();
// const { data } = useFetch("/api/admin/stats");

definePageMeta({ layout: "admin" });
</script>

<template>
  <!-- <div class="grid">
    <div class="col-12 md:col-3">
      <Card class="text-center">
        <template #title>用户</template>
        <template #content>
          <div class="text-3xl font-bold">{{ data?.users || 0 }}</div>
          <div class="i-ri-user-line mt-2 text-2xl"></div>
        </template>
      </Card>
    </div>
    <div class="col-12 md:col-3">
      <Card class="text-center">
        <template #title>团队</template>
        <template #content>
          <div class="text-3xl font-bold">{{ data?.teams || 0 }}</div>
          <div class="i-ri-team-line mt-2 text-2xl"></div>
        </template>
      </Card>
    </div>
    <div class="col-12 md:col-3">
      <Card class="text-center">
        <template #title>项目</template>
        <template #content>
          <div class="text-3xl font-bold">{{ data?.projects || 0 }}</div>
          <div class="i-ri-folder-line mt-2 text-2xl"></div>
        </template>
      </Card>
    </div>
    <div class="col-12 md:col-3">
      <Card class="text-center">
        <template #title>访问量</template>
        <template #content>
          <div class="text-3xl font-bold">0</div>
          <div class="i-ri-bar-chart-line mt-2 text-2xl"></div>
        </template>
      </Card>
    </div>
  </div> -->
</template>
